### ISSUE TITLE
Clicking middle mouse button breaks scrolling

### ISSUE THREAD

**Issue by jelmerdemaat** [JoelBesada/scrollpath#1]
Using Chrome (on Windows 7, 64bit), clicking the mouse wheel and dragging the mouse takes the scroll effect away from the path. After this the normal scrolling with the mouse wheel is blocked.

(I know not many people use this feature of actually clicking the mouse wheel, but I find it a useful function, especially on my tablet pen.)

**Comment by JoelBesada** [comment]
All I can do for now is disable mouse wheel click scrolling altogether, but this only seems to work in webkit browsers.

The best solution would be to re-map the middle mouse button to use the custom scroll path, but I doubt it's possible to make a reliable cross-browser implementation for that.

**Comment by yairEO** [comment]
this sucks there is no middle click. I will never use such a plugin which breaks such an important feature
