### ISSUE TITLE
Starting from top left corner

### ISSUE THREAD

**Issue by peterloo** [JoelBesada/scrollpath#14]
Is there a way to get the wrapper to start from the top left hand corner of the browser window instead of centered?

Love this script.  Good work.

**Comment by JoelBesada** [comment]
You can edit the script at line 525 and 526 (the centeredX and centeredY values) to change the relative offset to the path. 

```
var centeredX = node.x,
    centeredY = node.y,
```

Replacing lines 525-526 with the code above should give you the desired effect.

**Comment by peterloo** [comment]
Wow, that was fast!  Thanks!  Works like a charm.

**Comment by Mat3o** [comment]
Also you can do this:

``` javascript
    topPoint = $( window ).height()/2;
    leftPoint = $( window ).width()/2;

    $.fn.scrollPath("getPath").moveTo( leftPoint, topPoint , {name: "start"});
```

It works in my case.
