### ISSUE TITLE
This thing is fantastic.

### ISSUE THREAD

**Issue by jbeasley6651** [JoelBesada/scrollpath#2]
A+ ~ Joel Beasley

**Comment by JoelBesada** [comment]
Thank you, I'm glad you think so. :)

**Comment by jbeasley6651** [comment]
:)

You gotta change your settings to accept messages on github, that's
why I posted in issues

Sent from my iPhone

On Feb 16, 2012, at 1:27 PM, Joel Besada
reply@reply.github.com
wrote:

**Comment by JoelBesada** [comment]
I can't seem to find where to do that, do you mind pointing me in the right direction?

**Comment by jbeasley6651** [comment]
account settings > emails
