### ISSUE TITLE
adding oversized bg layer

### ISSUE THREAD

**Issue by YoSev** [JoelBesada/scrollpath#28]
Hello,

i am trying to use your script for an oversized background-layer, to simply scroll / rotate etc. an oversized image (like 5000x5000px), as http://www.artofflightmovie.com/ shows off.
the well i made it working in a pretty low-way, but the performance is so heavy that i need a better solution.

any ideas how i could use/improve scrollPath to animate an oversized background image, instead of the content-wrapper?

thx,
john

**Comment by YoSev** [comment]
Here is my try, the image is copied from the page above, jsut for testing purposes..
http://v2.wepixel.de/files/wepixelv2/sp/

**Comment by YoSev** [comment]
Ok, looks like it's working fine on safari and chrome on os x, just firefox has those huge performance problems.. any ideas our there?

**Comment by BoomSolWebDev** [comment]
Hallo und Guten Tag,

vielen Dank für Ihre E-Mail. Ich werde bis einschließlich 14.04.2013 nicht im Büro erreichbar sein und keinen Zugriff auf meine E-Mails haben.

In dringenden Fällen kontaktieren Sie bitte meine Kollegen unter 0651-96680-70 oder per E-Mail an p.gerken@boomerang-solutions.de. Ansonsten bearbeite ich meine E-Mails nach meiner Rückkehr.

Vielen Dank für Ihr Verständnis und freundliche Grüße,

Tino Feist 

Hello and G'day

Thank you for your e-mail. I will be out of the office until 14th of April inclusive and will not have access to my e-mail account.

If you have an urgent query, please contact my colleagues via email p.gerken@boomerang-solutions.de or phone +49 651-96680-70.

In all other cases I will get back to you after my return.

Thank you very much for your understanding and best regards,

Tino Feist
