### ISSUE TITLE
Use Scroll Path On An Element

### ISSUE THREAD

**Issue by veganista** [JoelBesada/scrollpath#8]
First off, you've done a great job on this, it looks well good.

Have you got any tips to get this - http://dabblet.com/gist/1966261 working without an iframe.

I know it's in the wish list for features and i was wondering if you had made any progress.

For my needs i only need to be able to use one instance on a page, just not on the whole page.

Any ideas?

**Comment by JoelBesada** [comment]
As I'm busy with other things, I haven't been able to work on this yet. I hope you can work around that limitation somehow. Since the feature already is in the wish list, I'll close this issue.
